name: Lint

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        components:
          - rustfmt
          - clippy
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: ${{ matrix.components }}
      - name: Format
        if: ${{ matrix.components == 'rustfmt' }}
        run: cargo fmt --all -- --check
      - name: Lint
        if: ${{ matrix.components == 'clippy' }}
        run: cargo clippy --all-targets --all-features -- -D warnings